Create SECURITY.md
RobinsMediaTeam/Cardboard pull request #30
Opened 2022-06-30 20:46 UTC by ThatOneNovaGuy

Just the template, needs refinement.

2022-07-08 22:28 UTC, ThatOneNovaGuy reviewed
SECURITY.md will be refined at a later date, pushing for now.

2022-07-11 09:10 UTC, JeffreyBlinksma approved these changes, later dismissed

2022-07-14 18:30 UTC, ghost reviewed
Looks good

2022-07-18 05:30 UTC, LameLemon requested changes
Just wanted to clarify the commit hashes for the release tags are correct. I can't locate them in the orignal repo's, let me know if I'm looking at it wrong. Thanks! : )

2022-07-18 05:30 UTC, LameLemon commented on .github/workflows/codeql-analysis.yml
> +      uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
Is this the commit hash?

It gives a 404.
https://github.com/actions/checkout/commit/d0651293c4a5a52e711f25b41b05b2212f385d28

v3 commit hash looks to be `2541b1294d2704b0964813337f33b291d3f8596b`. Let me know if I'm reading this right. :slightly_smiling_face:

2022-07-18 05:30 UTC, LameLemon commented on .github/workflows/codeql-analysis.yml
> +      uses: github/codeql-action/init@5a54a995785650c9dbc4c88cc1e1d1b4df4302a8
All of the codeql-action commit hashes give out a 404. The commit hash for v2 seems to be 3e7e3b32d0fb8283594bb0a76cc60a00918b0969.

https://github.com/github/codeql-action/commit/5a54a995785650c9dbc4c88cc1e1d1b4df4302a8

2022-11-21 17:24 UTC, closed without merging

2022-11-21 17:24 UTC, ThatOneNovaGuy commented
Stale branch, should fix most issues by resolving other PR's.